/**
 * MOCK RENT STORE — prototype state only, NOT a backend.
 * ------------------------------------------------------
 * Holds invoices, payments, the tenant credit ledger, move-outs and rent
 * settings in React state. Every number it reports is computed by the pure
 * functions in `rent-engine.ts`; this file only stores rows and dispatches
 * actions. Swap the seeds for Supabase queries and keep the same API.
 */
import { createContext, useContext, useMemo, useState, type ReactNode } from "react";
import { leases as allLeases, unitById } from "@/lib/mock-data";
import {
  addMonths,
  balanceCents,
  creditBalanceCents,
  creditToApply,
  generateMonthlyInvoices,
  nextRunDate,
  periodOf,
  periodLabel,
  toCents,
  type CreditEntry,
  type Invoice,
  type InvoiceKind,
  type MoveOut,
  type Payment,
  type PaymentMethod,
  type RentSettings,
} from "@/lib/rent-engine";

/** MOCK: the demo "today". A backend would use the server clock. */
export const TODAY = "2026-08-12";
const CURRENT_PERIOD = periodOf(TODAY);

const defaultSettings: RentSettings = {
  invoiceDay: 1,
  autoApplyCredit: true,
  autoApplyLastMonth: true,
};

// —— seeds ——————————————————————————————————————————————
// Four months of history generated by the same engine the app uses live.
function seedInvoices(): Invoice[] {
  const periods = [addMonths(CURRENT_PERIOD, -3), addMonths(CURRENT_PERIOD, -2), addMonths(CURRENT_PERIOD, -1), CURRENT_PERIOD];
  let out: Invoice[] = [];
  for (const period of periods) {
    out = out.concat(
      generateMonthlyInvoices({ leases: allLeases, existing: out, period, settings: defaultSettings, moveOuts: [] }),
    );
  }
  // MOCK one-off charges so the manual path has something to show.
  out.push({
    id: "inv-manual-water-1",
    tenantId: "t4",
    unitId: "u4",
    period: CURRENT_PERIOD,
    kind: "utilities",
    description: "Water & sewer share — July",
    amountCents: toCents(64.5),
    dueDate: `${CURRENT_PERIOD}-15`,
    issuedOn: `${CURRENT_PERIOD}-01`,
    auto: false,
    creditAppliedCents: 0,
  });
  return out;
}

function seedPayments(invoices: Invoice[]): Payment[] {
  const out: Payment[] = [];
  const methods: PaymentMethod[] = ["e-Transfer", "Pre-authorized debit", "Cheque", "Cash"];
  let n = 0;
  for (const inv of invoices) {
    if (inv.period === CURRENT_PERIOD) continue; // current month handled below
    out.push({
      id: `pay-seed-${++n}`,
      invoiceId: inv.id,
      tenantId: inv.tenantId,
      amountCents: inv.amountCents,
      method: methods[n % methods.length]!,
      receivedOn: inv.dueDate,
      reference: `REF-${String(1000 + n)}`,
    });
  }
  const current = (tenantId: string) =>
    invoices.find((i) => i.tenantId === tenantId && i.period === CURRENT_PERIOD && i.kind === "rent");
  const t1 = current("t1");
  if (t1) out.push({ id: "pay-seed-a", invoiceId: t1.id, tenantId: "t1", amountCents: t1.amountCents, method: "e-Transfer", receivedOn: `${CURRENT_PERIOD}-01`, reference: "REF-2001" });
  const t2 = current("t2");
  if (t2) out.push({ id: "pay-seed-b", invoiceId: t2.id, tenantId: "t2", amountCents: t2.amountCents, method: "Pre-authorized debit", receivedOn: `${CURRENT_PERIOD}-02`, reference: "REF-2002" });
  const t4 = current("t4");
  if (t4) out.push({ id: "pay-seed-c", invoiceId: t4.id, tenantId: "t4", amountCents: toCents(1000), method: "e-Transfer", receivedOn: `${CURRENT_PERIOD}-03`, reference: "REF-2003" });
  return out;
}

// MOCK: one historic overpayment. Last month's rent is a held deposit, not a
// credit — see `lastMonthHeldCents`.
function seedCredits(): CreditEntry[] {
  return [
    {
      id: "cr-1",
      tenantId: "t2",
      amountCents: toCents(45),
      reason: "Overpaid June rent",
      date: `${addMonths(CURRENT_PERIOD, -2)}-04`,
      kind: "overpayment",
    },
  ];
}

export const lastMonthHeldCents = (tenantId: string) => {
  const lease = allLeases.find((l) => l.tenantId === tenantId);
  return lease ? toCents(lease.depositHeld) : 0;
};

// —— context ————————————————————————————————————————————
type RentCtx = ReturnType<typeof useRentStore>;
const Ctx = createContext<RentCtx | null>(null);

function useRentStore() {
  const seededInvoices = useMemo(seedInvoices, []);
  const [invoices, setInvoices] = useState<Invoice[]>(seededInvoices);
  const [payments, setPayments] = useState<Payment[]>(() => seedPayments(seededInvoices));
  const [credits, setCredits] = useState<CreditEntry[]>(seedCredits);
  const [settings, setSettings] = useState<RentSettings>(defaultSettings);
  const [moveOuts, setMoveOuts] = useState<MoveOut[]>([]);
  const [savedMethods, setSavedMethods] = useState<SavedPaymentMethod[]>([
    { id: "sm1", tenantId: "t3", type: "bank", last4: "8821", brand: "TD Canada Trust", label: "TD Chequing", isDefault: true },
    { id: "sm2", tenantId: "t3", type: "card", last4: "4242", brand: "Visa", label: "Personal Visa", isDefault: false },
  ]);
  const [autopayConfigs, setAutopayConfigs] = useState<AutopayStatus[]>([
    { leaseId: "l3", tenantId: "t3", enabled: true, methodId: "sm1" },
  ]);


  const uid = (p: string) => `${p}-${Math.random().toString(36).slice(2, 9)}`;

  return useMemo(() => {
    const nextRun = nextRunDate(TODAY, settings.invoiceDay);
    const nextRunPeriod = periodOf(nextRun);

    /** Run the monthly generator for a period (idempotent). */
    const runInvoicing = (period: string) => {
      const created = generateMonthlyInvoices({
        leases: allLeases.filter((l) => !moveOuts.some((m) => m.tenantId === l.tenantId)),
        existing: invoices,
        period,
        settings,
        moveOuts,
        idPrefix: "inv",
      });
      if (created.length) setInvoices((prev) => [...prev, ...created]);
      return created.length;
    };

    const addManualInvoice = (input: {
      tenantId: string;
      kind: InvoiceKind;
      description: string;
      amountCents: number;
      dueDate: string;
    }) => {
      const unitId = allLeases.find((l) => l.tenantId === input.tenantId)?.unitId ?? "";
      const invoice: Invoice = {
        id: uid("inv"),
        tenantId: input.tenantId,
        unitId,
        period: periodOf(input.dueDate),
        kind: input.kind,
        description: input.description,
        amountCents: input.amountCents,
        dueDate: input.dueDate,
        issuedOn: TODAY,
        auto: false,
        creditAppliedCents: 0,
      };
      setInvoices((prev) => [...prev, invoice]);
      return invoice;
    };

    /** Record a payment. Overpayment becomes a tenant credit. */
    const recordPayment = (input: {
      invoiceId: string;
      amountCents: number;
      method: PaymentMethod;
      receivedOn: string;
      reference?: string;
      note?: string;
    }) => {
      const invoice = invoices.find((i) => i.id === input.invoiceId);
      if (!invoice) return null;
      const balance = balanceCents(invoice, payments);
      const applied = Math.min(input.amountCents, Math.max(balance, 0));
      const over = input.amountCents - applied;
      const payment: Payment = {
        id: uid("pay"),
        invoiceId: invoice.id,
        tenantId: invoice.tenantId,
        amountCents: applied,
        method: input.method,
        receivedOn: input.receivedOn,
        reference: input.reference?.trim() || "—",
        ...(input.note ? { note: input.note } : {}),
      };
      setPayments((prev) => [...prev, payment]);
      if (over > 0) {
        setCredits((prev) => [
          ...prev,
          { id: uid("cr"), tenantId: invoice.tenantId, amountCents: over, reason: `Overpayment on ${invoice.description}`, date: input.receivedOn, kind: "overpayment" },
        ]);
      }
      return { payment, overpaymentCents: over };
    };

    /** Correct a mis-entered payment: reverse the old row, write a new one. */
    const correctPayment = (paymentId: string, amountCents: number, method: PaymentMethod, receivedOn: string) => {
      const old = payments.find((p) => p.id === paymentId);
      if (!old) return;
      setPayments((prev) => [
        ...prev.map((p) => (p.id === paymentId ? { ...p, reversedOn: TODAY, reversalReason: "correction" as const } : p)),
        { ...old, id: uid("pay"), amountCents, method, receivedOn, note: "Correction of a mis-entered payment" },
      ]);
    };

    /** NSF: reverse the payment, raise an NSF charge, invoice returns to Overdue. */
    const reverseForNsf = (paymentId: string, feeCents: number) => {
      const old = payments.find((p) => p.id === paymentId);
      if (!old) return;
      const invoice = invoices.find((i) => i.id === old.invoiceId);
      setPayments((prev) => prev.map((p) => (p.id === paymentId ? { ...p, reversedOn: TODAY, reversalReason: "nsf" as const } : p)));
      if (feeCents > 0 && invoice) {
        setInvoices((prev) => [
          ...prev,
          {
            id: uid("inv"),
            tenantId: invoice.tenantId,
            unitId: invoice.unitId,
            period: periodOf(TODAY),
            kind: "nsf",
            description: `NSF charge — returned ${old.method.toLowerCase()}`,
            amountCents: feeCents,
            dueDate: TODAY,
            issuedOn: TODAY,
            auto: false,
            creditAppliedCents: 0,
          },
        ]);
      }
    };

    /** Apply available tenant credit to an invoice (never more than the balance). */
    const applyCredit = (invoiceId: string, requestedCents?: number) => {
      const invoice = invoices.find((i) => i.id === invoiceId);
      if (!invoice) return 0;
      const available = creditBalanceCents(credits, invoice.tenantId);
      const balance = balanceCents(invoice, payments);
      const amount = creditToApply(balance, requestedCents ?? available);
      if (amount <= 0) return 0;
      setInvoices((prev) => prev.map((i) => (i.id === invoiceId ? { ...i, creditAppliedCents: i.creditAppliedCents + amount } : i)));
      setCredits((prev) => [
        ...prev,
        { id: uid("cr"), tenantId: invoice.tenantId, amountCents: -amount, reason: `Applied to ${invoice.description}`, date: TODAY, kind: "applied" },
      ]);
      return amount;
    };

    /** Apply the held last month's rent to a final invoice. */
    const applyLastMonth = (invoiceId: string) => {
      const invoice = invoices.find((i) => i.id === invoiceId);
      if (!invoice) return 0;
      const held = lastMonthHeldCents(invoice.tenantId);
      const amount = creditToApply(balanceCents(invoice, payments), held);
      if (amount <= 0) return 0;
      setInvoices((prev) =>
        prev.map((i) => (i.id === invoiceId ? { ...i, creditAppliedCents: i.creditAppliedCents + amount, final: true } : i)),
      );
      setCredits((prev) => [
        ...prev,
        { id: uid("cr"), tenantId: invoice.tenantId, amountCents: 0, reason: `Last month's rent applied to ${invoice.description}`, date: TODAY, kind: "last-month" },
      ]);
      return amount;
    };

    /** Void an invoice: it stops being owed, but the row and its reason stay. */
    const voidInvoice = (invoiceId: string, reason: string) => {
      setInvoices((prev) =>
        prev.map((i) => (i.id === invoiceId ? { ...i, voidedOn: TODAY, voidReason: reason || "Cancelled by manager" } : i)),
      );
    };

    /** Move-out: stop future invoicing, disable the portal, keep every record. */
    const moveOut = (tenantId: string, movedOutOn: string, reason: string) => {
      const unitId = allLeases.find((l) => l.tenantId === tenantId)?.unitId ?? "";
      setMoveOuts((prev) => [...prev.filter((m) => m.tenantId !== tenantId), { tenantId, unitId, movedOutOn, reason, portalDisabled: true }]);
    };
    const undoMoveOut = (tenantId: string) => setMoveOuts((prev) => prev.filter((m) => m.tenantId !== tenantId));

    const toggleAutopay = (leaseId: string, tenantId: string, methodId: string, enabled: boolean) => {
      setAutopayConfigs(prev => {
        const filtered = prev.filter(a => a.leaseId !== leaseId);
        if (!enabled) return filtered;
        return [...filtered, { leaseId, tenantId, enabled, methodId }];
      });
    };

    const addPaymentMethod = (method: Omit<SavedPaymentMethod, "id">) => {
      const id = uid("sm");
      setSavedMethods(prev => {
        const next = method.isDefault ? prev.map(m => m.tenantId === method.tenantId ? { ...m, isDefault: false } : m) : prev;
        return [...next, { ...method, id }];
      });
      return id;
    };

    const removePaymentMethod = (id: string) => {
      setSavedMethods(prev => prev.filter(m => m.id !== id));
      setAutopayConfigs(prev => prev.filter(a => a.methodId !== id));
    };

    return {
      today: TODAY,
      invoices,
      payments,
      credits,
      settings,
      moveOuts,
      savedMethods,
      autopayConfigs,
      nextRun,
      nextRunPeriod,
      nextRunLabel: periodLabel(nextRunPeriod),
      leases: allLeases,
      unitOf: (unitId: string) => unitById(unitId),
      creditFor: (tenantId: string) => creditBalanceCents(credits, tenantId),
      isMovedOut: (tenantId: string) => moveOuts.some((m) => m.tenantId === tenantId),
      methodsForTenant: (tenantId: string) => savedMethods.filter(m => m.tenantId === tenantId),
      autopayForLease: (leaseId: string) => autopayConfigs.find(a => a.leaseId === leaseId),
      setSettings,
      runInvoicing,
      addManualInvoice,
      recordPayment,
      correctPayment,
      reverseForNsf,
      applyCredit,
      applyLastMonth,
      voidInvoice,
      moveOut,
      undoMoveOut,
      toggleAutopay,
      addPaymentMethod,
      removePaymentMethod,
    };

  }, [invoices, payments, credits, settings, moveOuts]);
}

export function RentProvider({ children }: { children: ReactNode }) {
  const value = useRentStore();
  return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
}

export function useRent() {
  const ctx = useContext(Ctx);
  if (!ctx) throw new Error("useRent must be used inside <RentProvider>");
  return ctx;
}
