/**
 * RENT ENGINE — deterministic money math.
 * ---------------------------------------
 * Every number on the Rent screen comes from these pure functions.
 * All amounts are INTEGER CENTS so arithmetic never drifts; only the
 * formatter converts back to dollars. No value here is ever guessed or
 * generated — same inputs always produce the same outputs.
 *
 * Shapes mirror future tables:
 *   invoices  -> rent_invoices
 *   payments  -> rent_payments (append-only; corrections are new rows)
 *   credits   -> tenant_credits (ledger, never mutated in place)
 */

export type InvoiceKind = "rent" | "utilities" | "damage" | "nsf" | "other";
export type InvoiceStatus = "paid" | "partial" | "overdue" | "due-soon" | "void";
export type PaymentMethod = "e-Transfer" | "Cheque" | "Cash" | "Pre-authorized debit";

export type Invoice = {
  id: string;
  tenantId: string;
  unitId: string;
  /** "2026-08" — the month this invoice covers (rent invoices are unique per lease+period) */
  period: string;
  kind: InvoiceKind;
  description: string;
  amountCents: number;
  dueDate: string;
  issuedOn: string;
  /** generated by the monthly run vs. added by hand */
  auto: boolean;
  /** cents settled from tenant credit / last month's rent, not from a payment */
  creditAppliedCents: number;
  /** true once the tenancy ended and this was the final invoice */
  final?: boolean;
  /** set when the invoice was cancelled; a voided invoice owes nothing */
  voidedOn?: string;
  voidReason?: string;
};


export type Payment = {
  id: string;
  invoiceId: string;
  tenantId: string;
  amountCents: number;
  method: PaymentMethod;
  receivedOn: string;
  reference: string;
  /** set when reversed (NSF) or corrected; a reversed payment counts for nothing */
  reversedOn?: string;
  reversalReason?: "nsf" | "correction";
  note?: string;
};

export type CreditEntry = {
  id: string;
  tenantId: string;
  /** positive = credit added, negative = credit consumed */
  amountCents: number;
  reason: string;
  date: string;
  kind: "overpayment" | "applied" | "last-month" | "manual";
};

export type RentSettings = {
  /** day of month invoices are generated and due */
  invoiceDay: number;
  autoApplyCredit: boolean;
  autoApplyLastMonth: boolean;
};

export type MoveOut = {
  tenantId: string;
  unitId: string;
  movedOutOn: string;
  reason: string;
  /** portal access is revoked on move-out; records stay readable */
  portalDisabled: boolean;
};

// ——— money primitives ———

export const toCents = (dollars: number) => Math.round(dollars * 100);
export const fromCents = (cents: number) => cents / 100;

/** Parses "1,234.5" / "$1234" / "1234.567" to exact cents. Returns null when not a number. */
export function parseAmountToCents(input: string): number | null {
  const cleaned = input.replace(/[^0-9.-]/g, "");
  if (!cleaned || cleaned === "-" || cleaned === ".") return null;
  const value = Number(cleaned);
  if (!Number.isFinite(value)) return null;
  return Math.round(value * 100);
}

export const money = (cents: number) =>
  new Intl.NumberFormat("en-CA", { style: "currency", currency: "CAD" })
    .format(fromCents(cents))
    .replace("$", "CA$");

// ——— dates ———

export const isoDay = (d: Date) => d.toISOString().slice(0, 10);
export const periodOf = (iso: string) => iso.slice(0, 7);

export function periodLabel(period: string) {
  const [y, m] = period.split("-").map(Number);
  return new Date(y!, (m ?? 1) - 1, 1).toLocaleDateString("en-CA", { month: "long", year: "numeric" });
}

export function addMonths(period: string, n: number) {
  const [y, m] = period.split("-").map(Number);
  const d = new Date(y!, (m ?? 1) - 1 + n, 1);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
}

/** The next monthly invoicing run: `invoiceDay` of this month if still ahead, else next month. */
export function nextRunDate(today: string, invoiceDay: number): string {
  const [y, m, d] = today.split("-").map(Number);
  const day = Math.min(invoiceDay, 28);
  if (d! < day) return `${y}-${String(m).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
  const next = new Date(y!, m!, 1); // first of next month
  return `${next.getFullYear()}-${String(next.getMonth() + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
}

// ——— derived invoice numbers ———

export const activePayments = (payments: Payment[], invoiceId: string) =>
  payments.filter((p) => p.invoiceId === invoiceId && !p.reversedOn);

export function paidCents(invoice: Invoice, payments: Payment[]) {
  return activePayments(payments, invoice.id).reduce((s, p) => s + p.amountCents, 0);
}

export function balanceCents(invoice: Invoice, payments: Payment[]) {
  if (invoice.voidedOn) return 0;
  return invoice.amountCents - invoice.creditAppliedCents - paidCents(invoice, payments);
}

export function invoiceStatus(invoice: Invoice, payments: Payment[], today: string): InvoiceStatus {
  if (invoice.voidedOn) return "void";
  const balance = balanceCents(invoice, payments);
  if (balance <= 0) return "paid";
  const settled = invoice.amountCents - balance;
  if (invoice.dueDate < today) return "overdue";
  if (settled > 0) return "partial";
  return "due-soon";
}

export function creditBalanceCents(credits: CreditEntry[], tenantId: string) {
  return credits.filter((c) => c.tenantId === tenantId).reduce((s, c) => s + c.amountCents, 0);
}

// ——— generation ———

export type LeaseLike = { id: string; unitId: string; tenantId: string; rent: number; end: string };

/**
 * Deterministic monthly run: one rent invoice per active lease per period.
 * Never creates a duplicate, never invoices a moved-out tenancy.
 */
export function generateMonthlyInvoices(args: {
  leases: LeaseLike[];
  existing: Invoice[];
  period: string;
  settings: RentSettings;
  moveOuts: MoveOut[];
  idPrefix?: string;
}): Invoice[] {
  const { leases, existing, period, settings, moveOuts } = args;
  const day = String(Math.min(settings.invoiceDay, 28)).padStart(2, "0");
  const dueDate = `${period}-${day}`;
  const out: Invoice[] = [];
  for (const lease of leases) {
    if (moveOuts.some((m) => m.tenantId === lease.tenantId && periodOf(m.movedOutOn) < period)) continue;
    const already = existing.some(
      (i) => i.kind === "rent" && i.tenantId === lease.tenantId && i.unitId === lease.unitId && i.period === period,
    );
    if (already) continue;
    out.push({
      id: `${args.idPrefix ?? "inv"}-${lease.id}-${period}`,
      tenantId: lease.tenantId,
      unitId: lease.unitId,
      period,
      kind: "rent",
      description: `Rent — ${periodLabel(period)}`,
      amountCents: toCents(lease.rent),
      dueDate,
      issuedOn: dueDate,
      auto: true,
      creditAppliedCents: 0,
    });
  }
  return out;
}

/** How much credit can be applied to an invoice — never more than the balance, never negative. */
export function creditToApply(balance: number, availableCredit: number) {
  return Math.max(0, Math.min(balance, availableCredit));
}

// ——— receipts ———

export type ReceiptLine = { date: string; description: string; method: string; amountCents: number };

export function receiptFor(invoice: Invoice, payments: Payment[]): ReceiptLine[] {
  return activePayments(payments, invoice.id).map((p) => ({
    date: p.receivedOn,
    description: invoice.description,
    method: p.method,
    amountCents: p.amountCents,
  }));
}

/** Yearly rent receipt: every non-reversed payment a tenant made in the calendar year. */
export function yearlyReceipt(args: { tenantId: string; year: number; invoices: Invoice[]; payments: Payment[] }) {
  const byId = new Map(args.invoices.map((i) => [i.id, i]));
  const lines = args.payments
    .filter((p) => p.tenantId === args.tenantId && !p.reversedOn && p.receivedOn.startsWith(String(args.year)))
    .sort((a, b) => a.receivedOn.localeCompare(b.receivedOn))
    .map((p) => ({
      date: p.receivedOn,
      description: byId.get(p.invoiceId)?.description ?? "Payment",
      method: p.method,
      amountCents: p.amountCents,
    }));
  return { lines, totalCents: lines.reduce((s, l) => s + l.amountCents, 0) };
}

// ——— CSV ———

const csvCell = (value: string | number) => {
  const s = String(value);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

export function toCsv(headers: string[], rows: (string | number)[][]) {
  return [headers, ...rows].map((r) => r.map(csvCell).join(",")).join("\n");
}

export function downloadFile(filename: string, contents: string, type = "text/csv;charset=utf-8") {
  const blob = new Blob([contents], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
